# Site settings
title:       Lance Arlaus
email:       your_email@example.com
author:      Lance Arlaus
description: "Software architecture and engineering through a wide-angled lens"
baseurl:     ""
url:         "http://blog.lancearlaus.com"
timezone:    America/New_York

# Google analytics
google_analytics:

#"UA-63648105-1"

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: lancearlaus-blog

# Social icons
show_social_icons: true
github_username: lancearlaus
stackoverflow_id:
twitter_username: lancearlaus
google_plus_id: lance.arlaus
linkedin_username: lancearlaus
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: true
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
